# Generated by Django 2.2.5 on 2019-09-24 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('user_id', models.BigIntegerField(null=True)),
                ('body', models.TextField()),
                ('tag', models.CharField(choices=[('found', '주웠어요'), ('lost', '잃어버렸어요')], default=1, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/images/%Y/%m/%d/%H/%M')),
                ('profile_url', models.URLField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='board/profile/%Y/%m/%d/%H/%M')),
                ('page_counter', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FriendsBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('user_id', models.BigIntegerField(null=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='friends/images/%Y/%m/%d/%H/%M')),
                ('profile_url', models.URLField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='friends/profile/%Y/%m/%d/%H/%M')),
                ('page_counter', models.BigIntegerField(default=0)),
            ],
        ),
    ]
