# Generated by Django 2.2.5 on 2019-09-17 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190917_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.CharField(choices=[('found', '찾았어요'), ('lost', '잃어버렸어요')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
