# Generated by Django 2.2.5 on 2019-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_board_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='profile',
            field=models.CharField(max_length=100),
        ),
    ]
