# Generated by Django 2.2.5 on 2019-09-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190918_0131'),
        ('app', '0010_auto_20190918_0124'),
    ]

    operations = [
    ]
