# Generated by Django 2.2.5 on 2019-09-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190918_0124'),
        ('app', '0011_auto_20190918_0131'),
    ]

    operations = [
    ]
