# Generated by Django 2.2.5 on 2019-09-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20190918_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='profile',
            field=models.CharField(max_length=150),
        ),
    ]
