# Generated by Django 2.2.5 on 2019-09-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190918_0354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromotionBoard',
            new_name='BoothPromotionBoard',
        ),
    ]
