# Generated by Django 2.2.5 on 2019-09-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20190918_0158'),
        ('app', '0014_auto_20190918_0404'),
    ]

    operations = [
    ]
