# Generated by Django 2.2.5 on 2019-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20190918_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='freeBoard/images/')),
                ('profile', models.CharField(max_length=150)),
                ('video', models.FileField(blank=True, null=True, upload_to='freeBoard/videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='board/images/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boothpromotionboard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='boothPromotionBoard/images/'),
        ),
        migrations.AlterField(
            model_name='boothpromotionboard',
            name='user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='friendsboard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='friends/images/'),
        ),
        migrations.AlterField(
            model_name='friendsboard',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
