# Generated by Django 2.2.5 on 2019-09-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190918_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='free/images/'),
        ),
        migrations.AlterField(
            model_name='freeboard',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='free/videos/'),
        ),
    ]
