# Generated by Django 2.2.5 on 2019-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190918_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
