# Generated by Django 2.2.5 on 2019-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_board_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsboard',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
