# Generated by Django 2.2.5 on 2019-09-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_friendsboard_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoothPromotionBoard',
        ),
        migrations.DeleteModel(
            name='FreeBoard',
        ),
    ]
