# Generated by Django 2.2.5 on 2019-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190920_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='photo_delete',
            field=models.CharField(choices=[('no', '기존 사진을 지우지 않습니다.'), ('yes', '기존 사진을 지웁니다.')], default=1, max_length=20, null=True),
        ),
    ]
