# Generated by Django 2.2.5 on 2019-09-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_board_photo_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='photo_delete',
        ),
    ]
