# Generated by Django 2.2.5 on 2019-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_board_photo_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='profile_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='profile',
            field=models.ImageField(null=True, upload_to='board/profile/%Y/%m/%d/%H/%M'),
        ),
    ]
