# Generated by Django 2.2.5 on 2019-09-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190923_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsboard',
            name='profile_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='friendsboard',
            name='profile',
            field=models.ImageField(null=True, upload_to='friends/profile/%Y/%m/%d/%H/%M'),
        ),
    ]
