# Generated by Django 2.2.5 on 2019-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190923_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='page_counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
